#%RAML 1.0 Trait

headers:
  Clint_id:
    type: string
    required: true
  clint_secret:
    type: 
    required: true
queryParameters:
  employe_special_id:
    displayName: special id
    required: true
         